#goal definition
bool runRequested
---
#result definition
bool tabletConnected
bool cloudFault
---
#feedback
bool connected
bool stow
bool deploy
bool teleopDrive
bool EStop
bool placePiLit
bool pickupPiLit
bool connectedEnabled
bool cancelAutoDrive
bool deployAllPiLits
bool retrieveAllPiLits
float64[] placeLatLong
string formationType
bool driveToWaypoint
float64[] driveToLatLong


